In [7]:
import re
import pandas as pd

In [8]:
f=open('WhatsApp Chat with Abhijeet.txt',encoding='utf-8')

In [9]:
data=f.read()

In [29]:
print(data)

In [11]:
pattern='\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s-\s'

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\Aalekh Vishwakarma\AppData\Local\Temp\ipykernel_8180\3706297391.py:1: SyntaxWarning: invalid escape sequence '\d'
  pattern='\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s-\s'

In [27]:
messages=re.split(pattern,data)[1:]
messages

In [28]:
dates=re.findall(pattern,data)
dates

In [22]:
df=pd.DataFrame({'user_message':messages,'message_date':dates})

df['message_date']=pd.to_datetime(df['message_date'],format='%m/%d/%y, %H:%M - ')

df.rename(columns={'message_date':'date'},inplace=True)

df.head()

                                        user_message                date
0  Messages and calls are end-to-end encrypted. O... 2025-06-30 11:31:00
1  Aalekh Vishwakarma: Abhijeet generative ke maj... 2025-06-30 11:32:00
2                                    Abhijeet: Haa\n 2025-06-30 11:35:00
3  Aalekh Vishwakarma: Aree boolean me nhi, strin... 2025-06-30 11:37:00
4                          Abhijeet: Accha accha 😂\n 2025-06-30 12:36:00

In [23]:
df.shape

(521, 2)

In [30]:
users=[]
messages=[]
for message in df['user_message']:
    entry=re.split('([\w\W]+?):\s',message)
    if entry[1:]:
        users.append(entry[1])
        messages.append(entry[2])
    else:
        users.append('group_notifications')
        messages.append(entry[0])

df['user']=users
df['message']=messages
df.drop(columns=['user_message'],inplace=True)

df.head()

<>:4: SyntaxWarning: invalid escape sequence '\w'
<>:4: SyntaxWarning: invalid escape sequence '\w'
C:\Users\Aalekh Vishwakarma\AppData\Local\Temp\ipykernel_8180\3253716947.py:4: SyntaxWarning: invalid escape sequence '\w'
  entry=re.split('([\w\W]+?):\s',message)

,date,user,message
0,2025-06-30 11:31:00,group_notifications,Messages and calls are end-to-end encrypted. O...
1,2025-06-30 11:32:00,Aalekh Vishwakarma,Abhijeet generative ke major topics bata sakte...
2,2025-06-30 11:35:00,Abhijeet,Haa\n
3,2025-06-30 11:37:00,Aalekh Vishwakarma,"Aree boolean me nhi, string me answer karna th..."
4,2025-06-30 12:36:00,Abhijeet,Accha accha 😂\n

In [37]:
df['year']=df['date'].dt.year

In [38]:
df.head()

,date,user,message,year,month
0,2025-06-30 11:31:00,group_notifications,Messages and calls are end-to-end encrypted. O...,2025,June
1,2025-06-30 11:32:00,Aalekh Vishwakarma,Abhijeet generative ke major topics bata sakte...,2025,June
2,2025-06-30 11:35:00,Abhijeet,Haa\n,2025,June
3,2025-06-30 11:37:00,Aalekh Vishwakarma,"Aree boolean me nhi, string me answer karna th...",2025,June
4,2025-06-30 12:36:00,Abhijeet,Accha accha 😂\n,2025,June

In [39]:
df['month']=df['date'].dt.month_name()

In [40]:
df.head()

,date,user,message,year,month
0,2025-06-30 11:31:00,group_notifications,Messages and calls are end-to-end encrypted. O...,2025,June
1,2025-06-30 11:32:00,Aalekh Vishwakarma,Abhijeet generative ke major topics bata sakte...,2025,June
2,2025-06-30 11:35:00,Abhijeet,Haa\n,2025,June
3,2025-06-30 11:37:00,Aalekh Vishwakarma,"Aree boolean me nhi, string me answer karna th...",2025,June
4,2025-06-30 12:36:00,Abhijeet,Accha accha 😂\n,2025,June

In [41]:
df['day']=df['date'].dt.day

In [42]:
df.head()

,date,user,message,year,month,day
0,2025-06-30 11:31:00,group_notifications,Messages and calls are end-to-end encrypted. O...,2025,June,30
1,2025-06-30 11:32:00,Aalekh Vishwakarma,Abhijeet generative ke major topics bata sakte...,2025,June,30
2,2025-06-30 11:35:00,Abhijeet,Haa\n,2025,June,30
3,2025-06-30 11:37:00,Aalekh Vishwakarma,"Aree boolean me nhi, string me answer karna th...",2025,June,30
4,2025-06-30 12:36:00,Abhijeet,Accha accha 😂\n,2025,June,30

In [43]:
df['hour']=df['date'].dt.hour

In [44]:
df['minute']=df['date'].dt.minute

In [45]:
df.head()

,date,user,message,year,month,day,hour,minute
0,2025-06-30 11:31:00,group_notifications,Messages and calls are end-to-end encrypted. O...,2025,June,30,11,31
1,2025-06-30 11:32:00,Aalekh Vishwakarma,Abhijeet generative ke major topics bata sakte...,2025,June,30,11,32
2,2025-06-30 11:35:00,Abhijeet,Haa\n,2025,June,30,11,35
3,2025-06-30 11:37:00,Aalekh Vishwakarma,"Aree boolean me nhi, string me answer karna th...",2025,June,30,11,37
4,2025-06-30 12:36:00,Abhijeet,Accha accha 😂\n,2025,June,30,12,36